version: "3.9"

services:
  main:
    container_name: misa-room
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment: 
      NODE_ENV: production
      APP_PORT: 8080
      REDIS_URL: redis://redis:6379
      CLOUD_NAME: <*****>
      API_KEY: <*******>
      API_SECRET: <**********>
    expose:
      - 8080
    links:
      - redis
    networks:
      - common

  redis:
    container_name: misa-room-redis
    image: redis:6.2.3-alpine
    ports:
      - 6379:6379
    networks:
      - common

networks:
  common:
